package com.mcverse.jobify.config;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Old H2 files still have job_posts.hourly_rate (NOT NULL), and very old rows have no rate yet. Retiring the column
 * (issue #55) must never cost a job its price. Each test builds an old-style table in its own in-memory database.
 */
class HourlyRateRetirementTest {

    private JdbcTemplate jdbc;
    private LegacySchemaPatch patch;

    @BeforeEach
    void oldSchema() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:hourly-" + UUID.randomUUID() + ";DB_CLOSE_DELAY=-1", "sa", "");
        jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("create table job_posts (post_id integer generated by default as identity primary key, "
                + "job_title varchar(255) not null, hourly_rate double not null, job_rating double not null, "
                + "rate double, rate_type varchar(255), employment_type varchar(255), work_mode varchar(255))");
        patch = new LegacySchemaPatch(jdbc);
    }

    @AfterEach
    void drop() {
        jdbc.execute("drop all objects");
    }

    private boolean hasColumn(String name) {
        return jdbc.queryForObject("select count(*) from information_schema.columns "
                + "where table_name = 'JOB_POSTS' and column_name = ?", Integer.class, name) > 0;
    }

    private void oldRow(String title, double hourly, Double rate, String rateType) {
        jdbc.update("insert into job_posts (job_title, hourly_rate, job_rating, rate, rate_type) values (?, ?, 0, ?, ?)",
                title, hourly, rate, rateType);
    }

    @Test
    void aVeryOldRowKeepsItsPriceAsAnHourlyRate() {
        oldRow("old", 75.0, null, null);

        patch.run(null);

        assertEquals(75.0, jdbc.queryForObject("select rate from job_posts", Double.class));
        assertEquals("HOURLY", jdbc.queryForObject("select rate_type from job_posts", String.class));
        assertTrue(!hasColumn("HOURLY_RATE"), "the column is dropped");
    }

    @Test
    void rowsThatAlreadyHaveARateAreLeftAlone() {
        oldRow("monthly", 30.0, 5200.0, "MONTHLY");
        oldRow("old", 40.0, null, null);

        patch.run(null);

        assertEquals(5200.0, jdbc.queryForObject("select rate from job_posts where job_title = 'monthly'", Double.class));
        assertEquals("MONTHLY", jdbc.queryForObject("select rate_type from job_posts where job_title = 'monthly'", String.class));
        assertEquals(40.0, jdbc.queryForObject("select rate from job_posts where job_title = 'old'", Double.class));
    }

    @Test
    void rateAndRateTypeBecomeRequiredOnceEveryRowHasThem() {
        oldRow("old", 50.0, null, null);
        patch.run(null);
        org.junit.jupiter.api.Assertions.assertThrows(RuntimeException.class,
                () -> jdbc.update("insert into job_posts (job_title, rate) values ('no type', 10)"));
    }

    @Test
    void runningTwiceChangesNothing() {
        oldRow("old", 60.0, null, null);
        patch.run(null);
        patch.run(null);
        assertEquals(60.0, jdbc.queryForObject("select rate from job_posts", Double.class));
        assertEquals(1, jdbc.queryForObject("select count(*) from job_posts", Integer.class));
    }

    @Test
    void anEmptyTableIsFine() {
        patch.run(null);
        assertTrue(!hasColumn("HOURLY_RATE"));
        assertNull(jdbc.queryForObject("select max(post_id) from job_posts", Integer.class));
    }

    @Test
    void jobRatingIsDroppedInTheSameRun() {
        oldRow("old", 10.0, null, null);
        patch.run(null);
        assertTrue(!hasColumn("JOB_RATING"));
    }
}
