package com.mcverse.jobify.tools;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/** The copy tool moves rows between two databases in dependency order, keeps values intact and fixes counters. */
class DatabaseCopyToolTest {

    // Child table is declared before its parent on purpose: the tool must order by foreign keys, not by name.
    private static final String SCHEMA = """
            create table a_child (id varchar(40) primary key, parent_id integer not null,
                                  note clob, active boolean not null, score double precision, created_at timestamp(6),
                                  born date);
            create table z_parent (id integer generated by default as identity primary key, name varchar(100) not null);
            alter table a_child add constraint fk_child_parent foreign key (parent_id) references z_parent (id);
            create table flyway_schema_history (installed_rank integer primary key);
            """;

    private Connection source;
    private Connection target;
    private final StringBuilder log = new StringBuilder();

    private static Connection newDb() throws SQLException {
        Connection c = DriverManager.getConnection(
                "jdbc:h2:mem:copytest-" + UUID.randomUUID() + ";DB_CLOSE_DELAY=-1", "sa", "");
        try (Statement st = c.createStatement()) {
            for (String sql : SCHEMA.split(";")) if (!sql.isBlank()) st.execute(sql);
        }
        return c;
    }

    @BeforeEach
    void setUp() throws SQLException {
        source = newDb();
        target = newDb();
        try (Statement st = source.createStatement()) {
            st.execute("insert into z_parent (id, name) values (7, 'seven'), (9, 'nine')");
            st.execute("insert into a_child values ('c1', 7, 'long text with ünïcode', true, 2.5, "
                    + "'2026-01-02 03:04:05.123456', '1990-05-06')");
            st.execute("insert into a_child values ('c2', 9, null, false, null, null, null)");
            st.execute("insert into flyway_schema_history values (1)");
        }
    }

    @AfterEach
    void tearDown() throws SQLException {
        source.close();
        target.close();
    }

    private DatabaseCopyTool tool() { return new DatabaseCopyTool(source, target, log); }

    private String one(String sql) throws SQLException {
        try (Statement st = target.createStatement(); ResultSet rs = st.executeQuery(sql)) {
            rs.next();
            return rs.getString(1);
        }
    }

    @Test
    void copiesEveryRowParentsFirstAndKeepsValues() throws SQLException {
        List<DatabaseCopyTool.TableResult> results = tool().copy(false, false);

        assertTrue(results.stream().allMatch(DatabaseCopyTool.TableResult::matches));
        assertEquals("2", one("select count(*) from a_child"));
        assertEquals("2", one("select count(*) from z_parent"));
        assertEquals("long text with ünïcode", one("select note from a_child where id = 'c1'"));
        assertEquals("TRUE", one("select active from a_child where id = 'c1'").toUpperCase());
        assertEquals("2.5", one("select score from a_child where id = 'c1'"));
        assertEquals("2026-01-02 03:04:05.123456", one("select created_at from a_child where id = 'c1'"));
        assertEquals("1990-05-06", one("select born from a_child where id = 'c1'"));
        assertNull(one("select note from a_child where id = 'c2'"));
        assertNull(one("select score from a_child where id = 'c2'"));
        assertTrue(log.indexOf("[z_parent, a_child]") >= 0, "parents are copied first: " + log);
    }

    @Test
    void doesNotCopyOrTouchTheMigrationHistory() throws SQLException {
        tool().copy(false, false);
        assertEquals("0", one("select count(*) from flyway_schema_history"));
    }

    @Test
    void identityCounterContinuesAboveTheLargestCopiedId() throws SQLException {
        tool().copy(false, false);
        try (Statement st = target.createStatement()) {
            st.execute("insert into z_parent (name) values ('new')");
        }
        assertEquals("10", one("select max(id) from z_parent"));
    }

    @Test
    void refusesANonEmptyTargetAndChangesNothing() throws SQLException {
        try (Statement st = target.createStatement()) {
            st.execute("insert into z_parent (id, name) values (1, 'existing')");
        }
        target.commit();
        IllegalStateException e = assertThrows(IllegalStateException.class, () -> tool().copy(false, false));
        assertTrue(e.getMessage().contains("--truncate"), e.getMessage());
        assertEquals("1", one("select count(*) from z_parent"));
        assertEquals("0", one("select count(*) from a_child"));
    }

    @Test
    void truncateEmptiesTheTargetFirstAndThenCopies() throws SQLException {
        try (Statement st = target.createStatement()) {
            st.execute("insert into z_parent (id, name) values (1, 'old')");
            st.execute("insert into a_child (id, parent_id, active) values ('old', 1, true)");
        }
        target.commit();
        tool().copy(true, false);
        assertEquals("2", one("select count(*) from z_parent"));
        assertEquals("0", one("select count(*) from z_parent where name = 'old'"));
        assertEquals("2", one("select count(*) from a_child"));
    }

    @Test
    void dryRunWritesNothing() throws SQLException {
        List<DatabaseCopyTool.TableResult> plan = tool().copy(false, true);
        assertEquals(2, plan.size());
        assertEquals("0", one("select count(*) from z_parent"));
        assertTrue(log.toString().contains("Dry run"));
    }

    @Test
    void refusesWhenTheSourceHasATableTheTargetLacks() throws SQLException {
        try (Statement st = source.createStatement()) {
            st.execute("create table only_in_source (id integer primary key)");
        }
        IllegalStateException e = assertThrows(IllegalStateException.class, () -> tool().copy(false, false));
        assertTrue(e.getMessage().contains("only_in_source"), e.getMessage());
    }

    @Test
    void aFailingTableIsRolledBackAndNamed() throws SQLException {
        try (Statement st = source.createStatement()) {
            st.execute("alter table a_child drop constraint fk_child_parent");
            st.execute("insert into a_child values ('c3', 404, null, true, null, null, null)"); // orphan row
        }
        IllegalStateException e = assertThrows(IllegalStateException.class, () -> tool().copy(false, false));
        assertTrue(e.getMessage().contains("a_child"), e.getMessage());
        assertEquals("0", one("select count(*) from a_child"), "the failed table is rolled back");
        assertFalse(log.toString().contains("All tables match"));
    }

    // ---------------------------------------------------------------------------------------- the command line

    private static String urlOf(Connection c) throws SQLException {
        return c.getMetaData().getURL();
    }

    private int run(java.io.ByteArrayOutputStream out, java.io.ByteArrayOutputStream err, String... args) {
        return DatabaseCopyTool.run(args, new java.io.PrintStream(out), new java.io.PrintStream(err));
    }

    @Test
    void commandLineCopiesAndExitsZero() throws SQLException {
        var out = new java.io.ByteArrayOutputStream();
        var err = new java.io.ByteArrayOutputStream();
        int code = run(out, err, "--source-url=" + urlOf(source), "--source-user=sa",
                "--target-url=" + urlOf(target), "--target-user=sa");
        assertEquals(0, code, err.toString());
        assertTrue(out.toString().contains("All tables match."));
        assertEquals("2", one("select count(*) from a_child"));
    }

    @Test
    void commandLineSupportsDryRunAndTruncate() throws SQLException {
        var out = new java.io.ByteArrayOutputStream();
        var err = new java.io.ByteArrayOutputStream();
        assertEquals(0, run(out, err, "--source-url=" + urlOf(source), "--source-user=sa",
                "--target-url=" + urlOf(target), "--target-user=sa", "--dry-run"));
        assertEquals("0", one("select count(*) from z_parent"));

        try (Statement st = target.createStatement()) {
            st.execute("insert into z_parent (id, name) values (1, 'old')");
        }
        target.commit();
        // refused without --truncate: exit code 1 and a readable message on stderr
        assertEquals(1, run(out, err, "--source-url=" + urlOf(source), "--source-user=sa",
                "--target-url=" + urlOf(target), "--target-user=sa"));
        assertTrue(err.toString().contains("--truncate"), err.toString());
        assertEquals(0, run(out, err, "--source-url=" + urlOf(source), "--source-user=sa",
                "--target-url=" + urlOf(target), "--target-user=sa", "--truncate"));
        assertEquals("2", one("select count(*) from z_parent"));
    }

    @Test
    void missingUrlsAreAUsageErrorWithExitCodeTwo() {
        var out = new java.io.ByteArrayOutputStream();
        var err = new java.io.ByteArrayOutputStream();
        assertEquals(2, run(out, err, "--source-url=jdbc:h2:mem:x"));
        assertTrue(err.toString().contains("--target-url"), err.toString());
        assertEquals(2, run(out, err));
    }

    @Test
    void anUnreachableDatabaseIsReportedNotThrown() {
        var out = new java.io.ByteArrayOutputStream();
        var err = new java.io.ByteArrayOutputStream();
        int code = run(out, err, "--source-url=jdbc:postgresql://127.0.0.1:1/none", "--source-user=x",
                "--target-url=jdbc:h2:mem:unused-target", "--target-user=sa");
        assertEquals(1, code);
        assertTrue(err.toString().startsWith("ERROR:"), err.toString());
    }
}
