-- Jobify baseline schema (PostgreSQL 18).
--
-- Derived from what Hibernate generates for the entities (schema-generation script on PostgreSQL 18), then
-- reviewed by hand. Differences from the raw Hibernate output, all deliberate:
--   * no CHECK constraints on enum columns: enum values are validated by Jackson/Hibernate, so adding an enum
--     constant never needs a migration (same decision as the VARCHAR mapping used with H2);
--   * constraints have readable names, foreign keys name their target column;
--   * indexes on foreign-key columns (PostgreSQL does not create them; Hibernate does not either).
-- Types are the plain SQL ones (varchar, bigint, integer, double precision, boolean, timestamp, text) so that a
-- port to another database is a mechanical rewrite: see docs/DATABASE_MIGRATION.md, section "To MySQL".
--
-- NEVER edit this file after it has been applied anywhere (Flyway checksums it). Change the schema with a new
-- V<n>__description.sql instead.

-- Identity: accounts for login ---------------------------------------------------------------------------------
create table app_users (
    id        bigint generated by default as identity primary key,
    username  varchar(255) not null,
    password  varchar(255) not null,
    role      varchar(255) not null,
    constraint uk_app_users_username unique (username)
);

-- Profiles (JOINED inheritance: users -> seekers / employers) --------------------------------------------------
create table users (
    id            varchar(255) primary key,
    username      varchar(255) not null,
    name          varchar(255) not null,
    last_name     varchar(255) not null,
    creation_date timestamp(6),
    constraint uk_users_username unique (username)
);

create table user_last_updates (
    user_id    varchar(255) not null,
    updated_at timestamp(6),
    constraint fk_user_last_updates_user foreign key (user_id) references users (id)
);

create table companies (
    id   varchar(255) primary key,
    name varchar(255) not null
);

create table employers (
    id         varchar(255) primary key,
    company_id varchar(255),
    constraint fk_employers_user    foreign key (id)         references users (id),
    constraint fk_employers_company foreign key (company_id) references companies (id)
);

create table cvs (
    id                 varchar(255) primary key,
    file_url           varchar(255),
    file_type          varchar(255),
    original_file_name varchar(255),
    file_date          timestamp(6)
);

create table job_preferences (
    id                      varchar(255) primary key,
    preferred_job_title     varchar(255),
    employment_type         varchar(255),
    experience_level        varchar(255),
    location_preferences    varchar(255),
    working_hours           varchar(255),
    min_salary_expectation  double precision not null,
    max_salary_expectation  double precision not null
);

create table seekers (
    id                  varchar(255) primary key,
    is_independent      boolean not null,
    cv_id               varchar(255),
    job_preferences_id  varchar(255),
    constraint uk_seekers_cv              unique (cv_id),
    constraint uk_seekers_job_preferences unique (job_preferences_id),
    constraint fk_seekers_user            foreign key (id)                 references users (id),
    constraint fk_seekers_cv              foreign key (cv_id)              references cvs (id),
    constraint fk_seekers_job_preferences foreign key (job_preferences_id) references job_preferences (id)
);

-- Seeker profile sections ------------------------------------------------------------------------------------------
create table education (
    id             varchar(255) primary key,
    seeker_id      varchar(255) not null,
    institution    varchar(255) not null,
    degree         varchar(255) not null,
    field_of_study varchar(255) not null,
    grade          varchar(255),
    start_date     date not null,
    end_date       date,
    constraint fk_education_seeker foreign key (seeker_id) references seekers (id)
);

create table certifications (
    id                   varchar(255) primary key,
    seeker_id            varchar(255) not null,
    name                 varchar(255) not null,
    issuing_organization varchar(255) not null,
    credential_id        varchar(255),
    credential_url       varchar(255),
    issue_date           date not null,
    expiration_date      date,
    constraint fk_certifications_seeker foreign key (seeker_id) references seekers (id)
);

create table professional_experience (
    id              varchar(255) primary key,
    seeker_id       varchar(255) not null,
    job_title       varchar(255) not null,
    company_name    varchar(255) not null,
    location        varchar(255),
    employment_type varchar(255),
    start_date      date not null,
    end_date        date,
    description     text,
    constraint fk_professional_experience_seeker foreign key (seeker_id) references seekers (id)
);

create table skills (
    id       varchar(255) primary key,
    name     varchar(255) not null,
    category varchar(255),
    constraint uk_skills_name unique (name)
);

create table seeker_skills (
    id                  varchar(255) primary key,
    seeker_id           varchar(255) not null,
    skill_id            varchar(255) not null,
    proficiency_level   varchar(255) not null,
    years_of_experience double precision,
    constraint uk_seeker_skills_seeker_skill unique (seeker_id, skill_id),
    constraint fk_seeker_skills_seeker foreign key (seeker_id) references seekers (id),
    constraint fk_seeker_skills_skill  foreign key (skill_id)  references skills (id)
);

-- Jobs -----------------------------------------------------------------------------------------------------------
create table job_posts (
    post_id         integer generated by default as identity primary key,
    employer_id     varchar(255),
    job_title       varchar(255) not null,
    job_description text,
    location        varchar(255),
    work_mode       varchar(255),
    employment_type varchar(255),
    rate            double precision,
    rate_type       varchar(255),
    hourly_rate     double precision not null,  -- hourly equivalent of rate; V2 drops it after the front end stops reading it
    job_rating      double precision not null,  -- deprecated, always 0; dropped in V2
    available       boolean not null,
    created_at      timestamp(6),
    constraint fk_job_posts_employer foreign key (employer_id) references employers (id)
);

create table job_required_skills (
    job_post_id integer      not null,
    skill_id    varchar(255) not null,
    constraint fk_job_required_skills_job   foreign key (job_post_id) references job_posts (post_id),
    constraint fk_job_required_skills_skill foreign key (skill_id)    references skills (id)
);

create table applications (
    id          varchar(255) primary key,
    job_post_id integer      not null,
    seeker_id   varchar(255) not null,
    status      varchar(255) not null,
    cover_note  varchar(2000),
    created_at  timestamp(6) not null,
    updated_at  timestamp(6) not null,
    constraint uk_application_seeker_job unique (seeker_id, job_post_id),
    constraint fk_applications_job    foreign key (job_post_id) references job_posts (post_id),
    constraint fk_applications_seeker foreign key (seeker_id)   references seekers (id)
);

create table saved_jobs (
    id          varchar(255) primary key,
    job_post_id integer      not null,
    seeker_id   varchar(255) not null,
    saved_at    timestamp(6) not null,
    constraint uk_saved_job_seeker_job unique (seeker_id, job_post_id),
    constraint fk_saved_jobs_job    foreign key (job_post_id) references job_posts (post_id),
    constraint fk_saved_jobs_seeker foreign key (seeker_id)   references seekers (id)
);

-- Notifications, account deletion, CMS ---------------------------------------------------------------------------
create table notifications (
    id                 varchar(255) primary key,
    recipient_username varchar(255) not null,
    type               varchar(255) not null,
    title              varchar(255) not null,
    body               varchar(1000) not null,
    is_read            boolean not null,
    job_id             integer,
    application_id     varchar(255),
    created_at         timestamp(6) not null
);

create table deletion_requests (
    id              varchar(255) primary key,
    username        varchar(255) not null,
    requester_role  varchar(255) not null,
    status          varchar(255) not null,
    reason          varchar(255),
    resolution_note varchar(255),
    requested_at    timestamp(6) not null,
    resolved_at     timestamp(6)
);

create table content_entries (
    content_key   varchar(255) primary key,
    category      varchar(255) not null,
    content_value varchar(4000) not null,
    updated_at    timestamp(6) not null
);

-- Indexes (foreign keys and the lookups the API does) -------------------------------------------------------------
create index idx_notification_recipient_created on notifications (recipient_username, created_at);
create index idx_employers_company              on employers (company_id);
create index idx_education_seeker               on education (seeker_id);
create index idx_certifications_seeker          on certifications (seeker_id);
create index idx_professional_experience_seeker on professional_experience (seeker_id);
create index idx_job_posts_employer             on job_posts (employer_id);
create index idx_job_posts_available_created    on job_posts (available, created_at);
create index idx_job_required_skills_job        on job_required_skills (job_post_id);
create index idx_applications_job               on applications (job_post_id);
create index idx_saved_jobs_job                 on saved_jobs (job_post_id);
create index idx_user_last_updates_user         on user_last_updates (user_id);
create index idx_deletion_requests_status       on deletion_requests (status);
